### ISSUE TITLE
Document details of minimal autoproj installation

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-core/tools-pocolog2msgpack#9]
1. Pull rock bootstrap script
2. This:

```yaml
package_sets:
   - github: rock-core/package_set

layout:
   - tools/pocolog2msgpack

exclude_packages:
   - gui/
```
